name: generate test coverage

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install
      - run: npm test
      - name: Generate Code Test Coverage
        uses: luk-schweizer/jest-code-coverage-badge-action@v1.0.0
        with:
          kvaas-key-url: 'https://api.keyvalue.xyz/437c1f94/coverage'
